import { describe, expect, it } from "vitest";
import fixture from "./fixtures/app-state.json";
import { errorResponse, explainAfterRetry, toAppError, withRetry } from "./client";
import { appStateSchema, ipcErrorKindSchema, itemStatusSchema, operationOutcomeSchema, pendingLinkSchema, scheduledSyncSchema } from "./schemas";

// Generated by the Rust test app_state::tests::app_state_fixture_matches_the_checked_in_contract (UPDATE_FIXTURES=1).
const payload: unknown = fixture;

/** The same object as an older backend would send it, without the named fields. */
function without(value: object, keys: readonly string[]): Record<string, unknown> {
  return Object.fromEntries(Object.entries(value).filter(([key]) => !keys.includes(key)));
}

/** Tauri rejects with the backend's plain error object, not an Error; these tests exercise exactly that. */
async function rejectWith(reason: unknown): Promise<never> {
  // eslint-disable-next-line @typescript-eslint/prefer-promise-reject-errors -- the IPC boundary rejects with plain objects.
  return Promise.reject(reason);
}

function withItems(items: readonly unknown[]): unknown {
  return { ...fixture, items };
}

describe("AppState contract", () => {
  it("parses a realistic backend payload", () => {
    const state = appStateSchema.parse(payload);
    // z.object strips unknown keys, so a field the schema forgets would vanish here without this.
    expect(state).toEqual(fixture);
    expect(state.items.map((item) => item.id)).toEqual(fixture.items.map((item) => item.id));
    expect(state.items.slice(0, 3).map((item) => item.id)).toEqual(["official/publish", "team-data/sql-helper", "team-data/chart-style"]);
    expect(state.sources.map((source) => source.sourceId)).toEqual(["official", "team-data"]);
    expect(state.items[1]?.components.map((component) => component.status)).toEqual(["installed", "available"]);
  });

  it("parses the same state inside a scheduled sync event", () => {
    expect(scheduledSyncSchema.parse({ kind: "updated", state: payload }).kind).toBe("updated");
  });

  it("reads a failed scheduled sync", () => {
    const parsed = scheduledSyncSchema.parse({ kind: "failed", error: { kind: "offline", message: "You're offline." } });
    expect(parsed.kind === "failed" ? toAppError(parsed.error).summary : null).toBe("You're offline.");
  });

  it("ignores fields a newer backend adds", () => {
    const state = appStateSchema.parse({ ...fixture, futureField: true, items: fixture.items.map((item) => ({ ...item, futureField: 1 })) });
    expect(state.items).toHaveLength(fixture.items.length);
  });

  it("drops one malformed package instead of rejecting the whole state", () => {
    const [first, ...rest] = fixture.items;
    const state = appStateSchema.parse(withItems([{ ...first, status: "melted" }, ...rest]));
    expect(state.items.map((item) => item.id)).toEqual(rest.map((item) => item.id));
  });

  it("drops one malformed source instead of rejecting the whole state", () => {
    const state = appStateSchema.parse({ ...fixture, sources: [{ name: "broken" }, ...fixture.sources] });
    expect(state.sources).toHaveLength(2);
  });

  it("fills the offline and restore fields when an older backend leaves them out", () => {
    const state = appStateSchema.parse({
      ...without(fixture, ["connectivity", "syncInProgress"]),
      autoUpdateReport: { updatedItems: [], failedItems: [] },
      sources: fixture.sources.map((source) => without(source, ["lastSuccessAtEpochSeconds"]))
    });
    expect(state.connectivity).toBe("online");
    expect(state.syncInProgress).toBe(false);
    expect(state.autoUpdateReport.repairedItems).toEqual([]);
    expect(state.autoUpdateReport.extendedItems).toEqual([]);
    expect(state.sources.map((source) => source.lastSuccessAtEpochSeconds)).toEqual([null, null]);
    expect(operationOutcomeSchema.parse({ backupPaths: [] }).warnings).toEqual([]);
  });

  it("fills the marketplace fields an older backend leaves out", () => {
    const state = appStateSchema.parse({
      ...without(fixture, ["bundles"]),
      identity: without(fixture.identity, ["namespaces", "teams", "suggestionsWaiting"]),
      autoUpdateReport: without(fixture.autoUpdateReport, ["removedItems"]),
      items: fixture.items.map((item) => (item.marketplace === null ? item : { ...item, marketplace: without(item.marketplace, ["sharedWithYou"]) }))
    });
    expect(state.bundles).toEqual([]);
    expect(state.identity).toMatchObject({ namespaces: [], teams: [], suggestionsWaiting: 0 });
    expect(state.autoUpdateReport.removedItems).toEqual([]);
    expect(state.items.every((item) => item.marketplace?.sharedWithYou !== true)).toBe(true);
  });

  it("drops the old single tutorial app and offers nothing until the backend says so", () => {
    const state = appStateSchema.parse({ ...without(fixture, ["tutorialOffered", "promptApps"]), tutorial: "cursor" });
    expect(state.tutorialOffered).toBe(false);
    expect(state.promptApps).toEqual([]);
  });

  it("reads the links the app is opened with", () => {
    expect(pendingLinkSchema.parse(null)).toBeNull();
    expect(pendingLinkSchema.parse({ kind: "install", namespace: "team-data", id: "kit", component: null })).toEqual({ kind: "install", namespace: "team-data", id: "kit", component: null });
    expect(pendingLinkSchema.safeParse({ kind: "uninstall", namespace: "team-data", id: "kit", component: null }).success).toBe(false);
  });

  it("reads the offline, stale and missing values", () => {
    const [source, ...sources] = fixture.sources;
    const [item, ...items] = fixture.items;
    const state = appStateSchema.parse({
      ...fixture,
      connectivity: "degraded",
      syncInProgress: true,
      sources: [{ ...source, status: "stale", lastSuccessAtEpochSeconds: 1789990000 }, ...sources],
      items: [{ ...item, status: "missing" }, ...items]
    });
    expect(state.connectivity).toBe("degraded");
    expect(state.sources[0]?.status).toBe("stale");
    expect(state.sources[0]?.lastSuccessAtEpochSeconds).toBe(1789990000);
    expect(state.items[0]?.status).toBe("missing");
  });

  it("covers every status the fixture uses", () => {
    for (const item of fixture.items) {
      expect(itemStatusSchema.safeParse(item.status).success).toBe(true);
    }
  });
});

describe("toAppError", () => {
  it("keeps a plain string error behind the plain summary", () => {
    expect(toAppError("os error 32", "Couldn't install Publish.")).toEqual({ kind: null, summary: "Couldn't install Publish.", detail: "os error 32" });
  });

  it("reads a typed backend error", () => {
    expect(toAppError({ kind: "offline", message: "You're offline.", detail: "dns error" }, "Couldn't check your sources for updates.")).toEqual({
      kind: "offline",
      summary: "Couldn't check your sources for updates. You're offline.",
      detail: "dns error"
    });
  });

  it("reports unreadable data as a bug", () => {
    const parsed = appStateSchema.safeParse({});
    expect(parsed.success).toBe(false);
    expect(parsed.success ? null : toAppError(parsed.error).kind).toBe("bug");
  });

  it("shows a bug as something went wrong, with the backend text behind Details", () => {
    expect(toAppError({ kind: "bug", message: "index out of bounds", detail: "at planner.rs:12" }, "Couldn't install Publish.")).toEqual({
      kind: "bug",
      summary: "Couldn't install Publish. Something went wrong.",
      detail: "index out of bounds\nat planner.rs:12"
    });
  });
});

describe("error kinds", () => {
  it("maps each kind to what the window does", () => {
    expect(Object.fromEntries(ipcErrorKindSchema.options.map((kind) => [kind, errorResponse(kind)]))).toEqual({
      offline: "offline",
      locked: "retry",
      retryable: "retry",
      needsUser: "show",
      bug: "show"
    });
    expect(errorResponse(null)).toBe("show");
  });

  it("retries a locked file once, then gives up", async () => {
    let calls = 0;
    let retries = 0;
    const locked = { kind: "locked", message: "Claude Desktop is using a file." };
    const task = (): Promise<string> => {
      calls += 1;
      return calls === 1 ? rejectWith(locked) : Promise.resolve("done");
    };
    await expect(
      withRetry(
        task,
        () => {
          retries += 1;
        },
        0
      )
    ).resolves.toBe("done");
    expect([calls, retries]).toEqual([2, 1]);
    await expect(
      withRetry(
        async () => rejectWith(locked),
        () => undefined,
        0
      )
    ).rejects.toBe(locked);
  });

  it("does not retry what a retry cannot fix", async () => {
    let calls = 0;
    const needsUser = { kind: "needsUser", message: "Sign in to Windows first." };
    await expect(
      withRetry(
        () => {
          calls += 1;
          return rejectWith(needsUser);
        },
        () => undefined,
        0
      )
    ).rejects.toBe(needsUser);
    expect(calls).toBe(1);
  });

  it("tells the person which app to close when the message names one", () => {
    const locked = toAppError({ kind: "locked", message: "Claude Desktop is using its settings file." }, "Couldn't install Publish.");
    expect(explainAfterRetry(locked, ["Claude Desktop", "ChatGPT"]).summary).toBe("Couldn't install Publish. Claude Desktop is using its settings file. Close Claude Desktop and try again.");
    expect(explainAfterRetry(toAppError({ kind: "locked", message: "A file is in use." }), []).summary).toBe("A file is in use. Another program is using these files. Close it, then try again.");
    expect(explainAfterRetry(toAppError({ kind: "retryable", message: "The server timed out." }), []).summary).toBe("The server timed out. Try again in a moment.");
    const needsUser = toAppError({ kind: "needsUser", message: "Sign in first." });
    expect(explainAfterRetry(needsUser, ["Claude Desktop"])).toBe(needsUser);
  });
});
