// <auto-generated />
using System;
using Marketplace.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Api.Data.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260905213937_AddAccessRules")]
    partial class AddAccessRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Api.Data.AccessRule", b =>
                {
                    b.Property<string>("Target")
                        .HasMaxLength(81)
                        .HasColumnType("character varying(81)");

                    b.PrimitiveCollection<string[]>("Groups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("Users")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Target");

                    b.ToTable("AccessRules");
                });

            modelBuilder.Entity("Marketplace.Api.Data.ClientEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("Agents")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageId")
                        .HasMaxLength(81)
                        .HasColumnType("character varying(81)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "PackageId", "OccurredAt");

                    b.HasIndex("Account", "Kind", "OccurredAt", "PackageId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Marketplace.Api.Data.Heartbeat", b =>
                {
                    b.Property<string>("Account")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("Agents")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<string[]>("Installed")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OsBuild")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Account");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("Marketplace.Api.Data.NamespaceArchive", b =>
                {
                    b.Property<string>("Namespace")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackageCount")
                        .HasColumnType("integer");

                    b.HasKey("Namespace");

                    b.ToTable("NamespaceArchives");
                });

            modelBuilder.Entity("Marketplace.Api.Data.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Namespace", "PackageId")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Marketplace.Api.Data.PackageReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(81)
                        .HasColumnType("character varying(81)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Marketplace.Api.Data.PackageVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Changelog")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.PrimitiveCollection<string[]>("ComponentKinds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Yanked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique();

                    b.ToTable("PackageVersions");
                });

            modelBuilder.Entity("Marketplace.Api.Data.Publisher", b =>
                {
                    b.Property<string>("Namespace")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Namespace");

                    b.HasIndex("Account");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Marketplace.Api.Data.PackageVersion", b =>
                {
                    b.HasOne("Marketplace.Api.Data.Package", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Marketplace.Api.Data.Package", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
